### PR TITLE
Complete Spanish Translation

### PR DESCRIPTION
**Pull request by joseborges**
Complete Spanish Translation

### CODE REVIEW

**Comment by ihofmann** [comment]
Wow, muchas gracias

**Comment by joseborges** [comment]
Your welcome, and THANK YOU for making the open-websoccer source code available!

(PS: More translations are on the way, at least Italian and Portuguese)

**Comment by Requiao** [comment]
HI.
I have a Portuguese translation. I did the translation. And I use it on my website.

**Comment by joseborges** [comment]
Hi
Csn you zip it and send it to rootshell@ifreviews.org?

Thanks

**Pull request merged**
